### ISSUE TITLE
Sub API Problems

### ISSUE THREAD

**Issue by ther3y3s** [Decicus/DecAPI#114] opened 2024-05-13 18:23 UTC
/twitch/subcount/:channel and i think all subcount api
https://decapi.me/twitch/subcount/:channel

![image](https://github.com/Decicus/DecAPI/assets/35653733/e4cf517a-32ad-4d28-99b3-06e3cc1ef88a)

**Comment by Decicus** [comment] 2024-05-13 18:38
@ther3y3s Ah yeah, I know what the issue is here.

Until a fix has been released, remove any scopes from the URL that contain underscores (`_`). This should work for all required cases: https://decapi.me/auth/twitch?redirect=subcount&scopes=channel:read:subscriptions+user:read:email+moderator:read:followers+user:read:email

**Comment by ther3y3s** [comment] 2024-05-13 18:47
Works! Thanks!

**Closed as completed** 2024-05-13 18:55 UTC
